### PR TITLE
Add 'visvoro'  option

### LINKED ISSUE #45: Expected file list for zeo++ option with Boolean flag
I recently realized that when we are using `zeo++` flags like `res` where they accept Boolean flag, even if we set the flag to `False`, plugin still puts the expected output file in the list which results in crashing even though the calculations are done. 
The example on the effect of this issue happened in my `WorkChain` when I wanted to modify the `zeopp.parameters` at some point in the workchain and realized the issue. Currently, I resolved it by deleting the `key` from the dictionary but thought to report here, in case, we decide to fix it.

### PR DESCRIPTION
**Pull request by ltalirz**
* add `visVoro` option (that produces 3 output files)
 * fix #45 

resolving conflicts from #29

### CODE REVIEW

**Comment by ltalirz** [comment]
@pzarabadip I've tried to simplify your changes a bit. Can you give it a try with the new zeo++ executable?

One thing I don't really like is that this won't work with zeo++ 0.3 - the code runs but it does (obviously) not produce the expected output files if the `visVoro` option is specified.
The question is: is this option obscure enough that people won't notice?
Mentioning also @danieleongari for comment.

**Comment by pzarabadip** [comment]
Thanks @ltalirz I just tested the plugin with new changes. Unfortunately, it does not work. The reason is that in order to keep the backward compatibility and also compatibility in `zeo++`, I only added the option to `visVoro` key in a way that it would only accept one user-specified prefix. However, the current implementation of plugin generates several prefixes which results in failure. 
If we only provide `out.Visvoro` as the output prefix, the problem should be solved.

**Comment by ltalirz** [comment]
@pzarabadip Thanks for the test and the instruction on what to change.

I've tried making the change now: https://github.com/ltalirz/aiida-zeopp/pull/38/commits/569b0d5bec55c18c70df8e7cc899cef18471e5de

Is this what is required?

**Comment by ltalirz** [comment]
After this issue is addressed, I will make a new aiida-zeopp release

**Comment by pzarabadip** [comment]
> @pzarabadip Thanks for the test and the instruction on what to change.
> 
> I've tried making the change now: [569b0d5](https://github.com/ltalirz/aiida-zeopp/commit/569b0d5bec55c18c70df8e7cc899cef18471e5de)
> 
> Is this what is required?

Thanks a lot @ltalirz . I just tested it also within my `WorkChain` and it works perfectly. I think we can merge it to the `master`.

**Comment by pzarabadip** [comment]
> After this PR is merged, I will make a new aiida-zeopp release

During the testing within my `WorkChain`, I found a possible bug/issue. I will open an issue about it right now. Then, we would discuss if it would be necessary to fix it before the release or we can do it later.

**Comment by ltalirz** [comment]
@pzarabadip does this PR look good to you now?

**Comment by pzarabadip** [comment]
@ltalirz yeah, I think so. Thanks a lot.

**Comment by ltalirz** [comment]
Ok, I'll make a new release tomorrow

**Pull request merged**
