### PR TITLE
Pr add count block and units

### PR DESCRIPTION
**Pull request by danieleongari**
See commit for explanation.

### CODE REVIEW

**Comment by ltalirz** [comment]
P.P.S.  Once this is decided, I think there are still a few changes needed (e.g. the information on the units should move inside the parsers, and they should return the appropriate dictionaries). But let's wait until the main decision is taken.

**Comment by danieleongari** [comment]
What you propose is very elegant solution,
however my purpose was not for visualisation but only to inform the user when he reads the output Dict. Your solution is still missing this purpose: so I would keep both.

In general, the two solutions are used in other plugins:
1) have the units in the final part of the label (e.g., typically in Zeopp, `Density_g/cm^3`)
2) have the units separated (e.g., typically in Raspa, `Density_average`, `Density_dev`, `Density_unit`).

I recently pointed to @yakutovicha the problem of having it sometimes spelled as `unit` and sometime `units`, that makes it even more confusing: https://github.com/yakutovicha/aiida-raspa/issues/26

I decided to implement it here as option (2) not to break the output API for `Density`, but simply adding an extra informative key.

**Comment by ltalirz** [comment]
If that is also the approach followed by others, then I'm fine with this.

I suggest two changes (which I will take care of myself):
 * I propose that we should have a `<quantity>_units` key for every quantity, regardless of whether it is already contained in the key name (which is anyhow a bit of a oddity of zeo++)
 * the additional keys should be added by the respective parsers

Sounds good>

**Comment by danieleongari** [comment]
Thanks,
it does sound good to me, only be careful to use `<quantity>_unit`, i.e., the singular (https://github.com/yakutovicha/aiida-raspa/issues/26)!

Daniele

**Comment by ltalirz** [comment]
Ok. I was thinking plural but I agree that singular is the more natural. Will use the singular.

**Pull request closed without merging**
